plugins {
    id('net.fabricmc.fabric-loom').version("${loom_version}").apply(false)
    id('net.fabricmc.fabric-loom-remap').version("${loom_version}").apply(false)
    id('com.replaymod.preprocess').version("${preprocessor_version}")
}

preprocess {
    strictExtraMappings = false

    def mc12001 = createNode("1.20.1", 1_20_01, "official")
    def mc12002 = createNode("1.20.2", 1_20_02, "official")
    def mc12003 = createNode("1.20.3", 1_20_03, "official")
    def mc12005 = createNode("1.20.5", 1_20_05, "official")

    def mc12101 = createNode("1.21.1", 1_21_01, "official")
    def mc12102 = createNode("1.21.2", 1_21_02, "official")
    def mc12104 = createNode("1.21.4", 1_21_04, "official")
    def mc12105 = createNode("1.21.5", 1_21_05, "official")
    def mc12106 = createNode("1.21.6", 1_21_06, "official")
    def mc12109 = createNode("1.21.9", 1_21_09, "official")
    def mc12110 = createNode("1.21.10", 1_21_10, "official")
    def mc12111 = createNode("1.21.11", 1_21_11, "official")
    def mc260100 = createNode("26.1", 26_01_00, "official")
    def mc260200 = createNode("26.2", 26_02_00, "official")
    def mc260300 = createNode("26.3", 26_03_00, "official")

    mc12001.link(mc12002, null)
    mc12002.link(mc12003, null)
    mc12003.link(mc12005, null)
    mc12005.link(mc12101, null)

    mc12101.link(mc12102, file('versions/mapping-1.21.1-1.21.2.txt'))
    mc12102.link(mc12104, null)
    mc12104.link(mc12105, null)
    mc12105.link(mc12106, null)
    mc12106.link(mc12109, file('versions/mapping-1.21.6-1.21.9.txt'))
    mc12109.link(mc12110, null)
    mc12110.link(mc12111, null)
    mc12111.link(mc260100, null)
    mc260100.link(mc260200, null)
    mc260200.link(mc260300, null)

    for (final def node in getNodes()) {
        findProject(node.project).ext.mcVersion = node.mcVersion
    }
}
