plugins {
    id "fabric-loom" version "1.7-SNAPSHOT" apply false
    id "maven-publish"
    id "com.replaymod.preprocess" version "88169fcbc9"
}

preprocess {
    def mc12001 = createNode("1.20.1", 1_20_01, "official")
    def mc12101 = createNode("1.21.1", 1_21_01, "official")
    def mc12102 = createNode("1.21.2", 1_21_02, "official")
    def mc12103 = createNode("1.21.3", 1_21_03, "official")
    def mc12104 = createNode("1.21.4", 1_21_04, "official")
    def mc12105 = createNode("1.21.5", 1_21_05, "official")
    def mc12107 = createNode("1.21.7", 1_21_07, "official")
    def mc12110 = createNode("1.21.10", 1_21_10, "official")

    mc12001.link(mc12101, null)
    mc12102.link(mc12101, null)
    mc12103.link(mc12101, null)
    mc12104.link(mc12101, null)
    mc12105.link(mc12101, null)
    mc12107.link(mc12101, null)
    mc12110.link(mc12101, null)
}