final int mcVersion = project.mcVersion
final boolean unobfuscated = mcVersion >= 26_00_00

apply plugin: unobfuscated ? 'net.fabricmc.fabric-loom' : 'net.fabricmc.fabric-loom-remap'
apply plugin: 'com.replaymod.preprocess'

ext {
    getVersionSuffix = {
        String buildNumber
        String buildType = 'build'
        if (System.getenv("CI_BUILD") == 'false') buildNumber = null
        else {
            if (System.getenv("PR_BUILD") != 'false') buildType = 'pr'
            buildNumber = System.getenv("GITHUB_RUN_NUMBER")
        }
        String versionSuffix = (buildNumber != null ? "+${buildType}.${buildNumber}" : "")
        return versionSuffix
    }
}

configurations {
    if (!unobfuscated) {
        modRuntimeOnly.exclude group: 'net.fabricmc', module: 'fabric-loader'
    }
}

repositories {
    mavenLocal()
    maven {
        name 'mavenCentral'
        url 'https://repo1.maven.org/maven2/'
    }
    maven {
        name 'MasaMaven'
        url 'https://masa.dy.fi/maven'
    }
    maven {
        name 'CjsahMaven'
        url 'https://server.cjsah.net:1002/maven/'
    }
    maven {
        name 'CurseMaven'
        url "https://www.cursemaven.com"
    }
}

loom {
    runConfigs.configureEach {
        runDir '../../run'
        var isJbr = System.getProperty('java.vm.vendor').contains('JetBrains')
        def args = [
                '-Dmixin.debug.export=true',
                '-DMC_DEBUG_ENABLED=true',
                '-DMC_DEBUG_DEV_COMMANDS=true'
        ]
        if (isJbr) {
            args.add("-XX:+AllowEnhancedClassRedefinition")
        }
        vmArgs args
    }

    runConfigs.client {
        ideConfigGenerated = true
        def proArgs = ["--username", "Dev"]
        programArgs proArgs
    }

    if (!unobfuscated) {
        mixin {
            useLegacyMixinAp = true
        }
    }

}

//remapJar {
//    remapperIsolation = true
//}

JavaVersion SOURCE_JAVA_VERSION
JavaVersion TARGET_JAVA_VERSION

if (mcVersion >= 260000) {
    SOURCE_JAVA_VERSION = JavaVersion.VERSION_25
    TARGET_JAVA_VERSION = JavaVersion.VERSION_25
} else if (mcVersion >= 12005) {
    SOURCE_JAVA_VERSION = JavaVersion.VERSION_21
    TARGET_JAVA_VERSION = JavaVersion.VERSION_21
} else if (mcVersion >= 11800) {
    SOURCE_JAVA_VERSION = JavaVersion.VERSION_17
    TARGET_JAVA_VERSION = JavaVersion.VERSION_17
} else if (mcVersion >= 11700) {
    SOURCE_JAVA_VERSION = JavaVersion.VERSION_16
    TARGET_JAVA_VERSION = JavaVersion.VERSION_16
} else {
    SOURCE_JAVA_VERSION = JavaVersion.VERSION_1_8
    TARGET_JAVA_VERSION = JavaVersion.VERSION_17
}
JavaVersion MIXIN_COMPATIBILITY_LEVEL = TARGET_JAVA_VERSION

dependencies {
    // from https://github.com/TISUnion/Carpet-TIS-Addition/blob/master/common.gradle#L41-L54
    def autoImplementation = { dep -> unobfuscated ? implementation(dep) : modImplementation(dep) }

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    if (!unobfuscated) {
        mappings loom.layered() {
            officialMojangMappings()
        }
    }

    autoImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // fabric-carpet
    autoImplementation("carpet:fabric-carpet:${project.carpet_core_version}")
    // jep
    include(autoImplementation 'jep:jep:2.24')
    // jsr305
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    // mixin-extras
    if (mcVersion < 12100) {
        include(modImplementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${project.mixinextras_version}")))
    }
}

String versionSuffix = project.getVersionSuffix()
String versionWithMC = "${project.mod_version}-mc${project.minecraft_version}${versionSuffix}"

version = 'v' + project.mod_version + versionSuffix
group = project.maven_group

base {
    archivesName.set(project.archives_base_name + '-mc' + project.minecraft_version)
}

processResources {
    from "gca.accesswidener"

    from("${rootDir}/icon.png") {
        into("assets/${project.mod_id}")
    }

    inputs.property "version", versionWithMC

    filesMatching("fabric.mod.json") {
        expand([
                "id"               : project.mod_id,
                "version"          : versionWithMC,
                "name"             : project.archives_base_name,
                "minecraft_support": project.minecraft_support_version
        ])
    }
}

java {
    withSourcesJar()
    sourceCompatibility = SOURCE_JAVA_VERSION
    targetCompatibility = TARGET_JAVA_VERSION
}

jar {
    from "LICENSE"
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}