org.gradle.jvmargs=-Xmx6G
#org.gradle.parallel=true

mod_id=gca
mod_name=GugleCarpetAddition
archives_base_name=gugle-carpet-addition
maven_group=dev.dubhe.gugle

mod_version=2.12.4
mc_version_range=1.20 26.2

loom_version=1.16-SNAPSHOT
preprocessor_version=c5abb4fb12
loader_version=0.19.2
mixinextras_version=0.4.1

release_channel=beta
required_mods=carpet
curseforge_id=662867
modrinth_id=UHjbX5mk