name: Mod Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/**
      - src/**
      - versions/**
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        distro: [ zulu ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      CI_BUILD: true
      PR_BUILD: false
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.distro }}
          java-version: ${{ matrix.java }}

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: ./gradlew build

      - name: Collect build artifacts
        if: ${{ runner.os == 'Linux' }}
        run: |
          set -euo pipefail
          rm -rf artifacts
          mkdir -p artifacts

          while IFS= read -r -d '' f; do
            cp -v "$f" artifacts/
          done < <(
            find . -type f -path "*/build/libs/*.jar" \
            ! -name "*-sources.jar" \
            -print0
          )

      - name: Upload build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            artifacts/

      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/heads/releases/') }}
        run: ./gradlew publishMods
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

